export const WeatherData = {
    "payload": {
        "normalWeatherDto": {
            "HeWeather6": [
                {
                    "basic": {
                        "cid": "CN101110101",
                        "location": "西安",
                        "parent_city": "西安",
                        "admin_area": "陕西",
                        "cnty": "中国",
                        "lat": "34.26316071",
                        "lon": "108.94802094",
                        "tz": "+8.00"
                    },
                    "update": {
                        "loc": "2019-08-26 06:45",
                        "utc": "2019-08-25 22:45"
                    },
                    "status": "ok",
                    "now": {
                        "cloud": "91",
                        "cond_code": "101",
                        "cond_txt": "多云",
                        "fl": "26",
                        "hum": "91",
                        "pcpn": "0.0",
                        "pres": "961",
                        "tmp": "23",
                        "vis": "3",
                        "wind_deg": "71",
                        "wind_dir": "东北风",
                        "wind_sc": "1",
                        "wind_spd": "3"
                    },
                    "daily_forecast": [
                        {
                            "cond_code_d": "305",
                            "cond_code_n": "305",
                            "cond_txt_d": "小雨",
                            "cond_txt_n": "小雨",
                            "date": "2019-08-26",
                            "hum": "89",
                            "mr": "01:17",
                            "ms": "15:58",
                            "pcpn": "9.1",
                            "pop": "76",
                            "pres": "962",
                            "sr": "06:13",
                            "ss": "19:17",
                            "tmp_max": "29",
                            "tmp_min": "21",
                            "uv_index": "0",
                            "vis": "13",
                            "wind_deg": "321",
                            "wind_dir": "西北风",
                            "wind_sc": "1-2",
                            "wind_spd": "6"
                        },
                        {
                            "cond_code_d": "305",
                            "cond_code_n": "305",
                            "cond_txt_d": "小雨",
                            "cond_txt_n": "小雨",
                            "date": "2019-08-27",
                            "hum": "76",
                            "mr": "02:13",
                            "ms": "16:57",
                            "pcpn": "0.0",
                            "pop": "25",
                            "pres": "964",
                            "sr": "06:14",
                            "ss": "19:15",
                            "tmp_max": "23",
                            "tmp_min": "19",
                            "uv_index": "1",
                            "vis": "24",
                            "wind_deg": "193",
                            "wind_dir": "西南风",
                            "wind_sc": "1-2",
                            "wind_spd": "8"
                        },
                        {
                            "cond_code_d": "100",
                            "cond_code_n": "100",
                            "cond_txt_d": "晴",
                            "cond_txt_n": "晴",
                            "date": "2019-08-28",
                            "hum": "54",
                            "mr": "03:17",
                            "ms": "17:52",
                            "pcpn": "0.0",
                            "pop": "25",
                            "pres": "961",
                            "sr": "06:15",
                            "ss": "19:14",
                            "tmp_max": "29",
                            "tmp_min": "16",
                            "uv_index": "10",
                            "vis": "25",
                            "wind_deg": "178",
                            "wind_dir": "南风",
                            "wind_sc": "1-2",
                            "wind_spd": "5"
                        },
                        {
                            "cond_code_d": "100",
                            "cond_code_n": "101",
                            "cond_txt_d": "晴",
                            "cond_txt_n": "多云",
                            "date": "2019-08-29",
                            "hum": "41",
                            "mr": "04:26",
                            "ms": "18:42",
                            "pcpn": "0.0",
                            "pop": "1",
                            "pres": "960",
                            "sr": "06:15",
                            "ss": "19:13",
                            "tmp_max": "31",
                            "tmp_min": "17",
                            "uv_index": "9",
                            "vis": "25",
                            "wind_deg": "119",
                            "wind_dir": "东南风",
                            "wind_sc": "1-2",
                            "wind_spd": "2"
                        },
                        {
                            "cond_code_d": "101",
                            "cond_code_n": "101",
                            "cond_txt_d": "多云",
                            "cond_txt_n": "多云",
                            "date": "2019-08-30",
                            "hum": "35",
                            "mr": "05:39",
                            "ms": "19:27",
                            "pcpn": "0.0",
                            "pop": "0",
                            "pres": "959",
                            "sr": "06:16",
                            "ss": "19:11",
                            "tmp_max": "29",
                            "tmp_min": "16",
                            "uv_index": "9",
                            "vis": "25",
                            "wind_deg": "177",
                            "wind_dir": "南风",
                            "wind_sc": "1-2",
                            "wind_spd": "6"
                        },
                        {
                            "cond_code_d": "100",
                            "cond_code_n": "101",
                            "cond_txt_d": "晴",
                            "cond_txt_n": "多云",
                            "date": "2019-08-31",
                            "hum": "48",
                            "mr": "06:51",
                            "ms": "20:07",
                            "pcpn": "0.0",
                            "pop": "0",
                            "pres": "960",
                            "sr": "06:17",
                            "ss": "19:10",
                            "tmp_max": "30",
                            "tmp_min": "17",
                            "uv_index": "9",
                            "vis": "25",
                            "wind_deg": "117",
                            "wind_dir": "东南风",
                            "wind_sc": "1-2",
                            "wind_spd": "11"
                        },
                        {
                            "cond_code_d": "101",
                            "cond_code_n": "101",
                            "cond_txt_d": "多云",
                            "cond_txt_n": "多云",
                            "date": "2019-09-01",
                            "hum": "52",
                            "mr": "08:03",
                            "ms": "20:44",
                            "pcpn": "0.0",
                            "pop": "5",
                            "pres": "962",
                            "sr": "06:18",
                            "ss": "19:09",
                            "tmp_max": "31",
                            "tmp_min": "16",
                            "uv_index": "9",
                            "vis": "24",
                            "wind_deg": "163",
                            "wind_dir": "东南风",
                            "wind_sc": "3-4",
                            "wind_spd": "19"
                        }
                    ],
                    "hourly": [
                        {
                            "cloud": "65",
                            "cond_code": "104",
                            "cond_txt": "阴",
                            "dew": "19",
                            "hum": "75",
                            "pop": "5",
                            "pres": "959",
                            "time": "2019-08-26 07:00",
                            "tmp": "24",
                            "wind_deg": "97",
                            "wind_dir": "东风",
                            "wind_sc": "1-2",
                            "wind_spd": "7"
                        },
                        {
                            "cloud": "61",
                            "cond_code": "104",
                            "cond_txt": "阴",
                            "dew": "19",
                            "hum": "73",
                            "pop": "5",
                            "pres": "959",
                            "time": "2019-08-26 08:00",
                            "tmp": "25",
                            "wind_deg": "96",
                            "wind_dir": "东风",
                            "wind_sc": "1-2",
                            "wind_spd": "3"
                        },
                        {
                            "cloud": "55",
                            "cond_code": "104",
                            "cond_txt": "阴",
                            "dew": "18",
                            "hum": "66",
                            "pop": "6",
                            "pres": "960",
                            "time": "2019-08-26 09:00",
                            "tmp": "26",
                            "wind_deg": "81",
                            "wind_dir": "东风",
                            "wind_sc": "1-2",
                            "wind_spd": "5"
                        },
                        {
                            "cloud": "50",
                            "cond_code": "101",
                            "cond_txt": "多云",
                            "dew": "17",
                            "hum": "59",
                            "pop": "7",
                            "pres": "960",
                            "time": "2019-08-26 10:00",
                            "tmp": "27",
                            "wind_deg": "73",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "10"
                        },
                        {
                            "cloud": "45",
                            "cond_code": "101",
                            "cond_txt": "多云",
                            "dew": "16",
                            "hum": "52",
                            "pop": "7",
                            "pres": "960",
                            "time": "2019-08-26 11:00",
                            "tmp": "28",
                            "wind_deg": "33",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "7"
                        },
                        {
                            "cloud": "52",
                            "cond_code": "101",
                            "cond_txt": "多云",
                            "dew": "16",
                            "hum": "51",
                            "pop": "11",
                            "pres": "961",
                            "time": "2019-08-26 12:00",
                            "tmp": "28",
                            "wind_deg": "51",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "6"
                        },
                        {
                            "cloud": "60",
                            "cond_code": "101",
                            "cond_txt": "多云",
                            "dew": "16",
                            "hum": "49",
                            "pop": "19",
                            "pres": "961",
                            "time": "2019-08-26 13:00",
                            "tmp": "29",
                            "wind_deg": "41",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "1"
                        },
                        {
                            "cloud": "68",
                            "cond_code": "101",
                            "cond_txt": "多云",
                            "dew": "17",
                            "hum": "48",
                            "pop": "19",
                            "pres": "961",
                            "time": "2019-08-26 14:00",
                            "tmp": "29",
                            "wind_deg": "52",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "10"
                        },
                        {
                            "cloud": "78",
                            "cond_code": "101",
                            "cond_txt": "多云",
                            "dew": "16",
                            "hum": "51",
                            "pop": "24",
                            "pres": "961",
                            "time": "2019-08-26 15:00",
                            "tmp": "28",
                            "wind_deg": "19",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "8"
                        },
                        {
                            "cloud": "89",
                            "cond_code": "101",
                            "cond_txt": "多云",
                            "dew": "16",
                            "hum": "54",
                            "pop": "55",
                            "pres": "961",
                            "time": "2019-08-26 16:00",
                            "tmp": "27",
                            "wind_deg": "46",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "9"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "104",
                            "cond_txt": "阴",
                            "dew": "17",
                            "hum": "56",
                            "pop": "55",
                            "pres": "961",
                            "time": "2019-08-26 17:00",
                            "tmp": "26",
                            "wind_deg": "75",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "4"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "19",
                            "hum": "67",
                            "pop": "55",
                            "pres": "959",
                            "time": "2019-08-26 18:00",
                            "tmp": "25",
                            "wind_deg": "77",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "6"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "21",
                            "hum": "77",
                            "pop": "77",
                            "pres": "959",
                            "time": "2019-08-26 19:00",
                            "tmp": "25",
                            "wind_deg": "40",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "10"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "23",
                            "hum": "87",
                            "pop": "77",
                            "pres": "959",
                            "time": "2019-08-26 20:00",
                            "tmp": "24",
                            "wind_deg": "17",
                            "wind_dir": "东北风",
                            "wind_sc": "1-2",
                            "wind_spd": "5"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "22",
                            "hum": "89",
                            "pop": "77",
                            "pres": "959",
                            "time": "2019-08-26 21:00",
                            "tmp": "23",
                            "wind_deg": "88",
                            "wind_dir": "东风",
                            "wind_sc": "1-2",
                            "wind_spd": "6"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "21",
                            "hum": "90",
                            "pop": "49",
                            "pres": "959",
                            "time": "2019-08-26 22:00",
                            "tmp": "22",
                            "wind_deg": "155",
                            "wind_dir": "东南风",
                            "wind_sc": "1-2",
                            "wind_spd": "5"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "20",
                            "hum": "92",
                            "pop": "61",
                            "pres": "959",
                            "time": "2019-08-26 23:00",
                            "tmp": "22",
                            "wind_deg": "330",
                            "wind_dir": "西北风",
                            "wind_sc": "1-2",
                            "wind_spd": "11"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "104",
                            "cond_txt": "阴",
                            "dew": "19",
                            "hum": "93",
                            "pop": "61",
                            "pres": "960",
                            "time": "2019-08-27 00:00",
                            "tmp": "22",
                            "wind_deg": "190",
                            "wind_dir": "南风",
                            "wind_sc": "1-2",
                            "wind_spd": "11"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "19",
                            "hum": "94",
                            "pop": "25",
                            "pres": "960",
                            "time": "2019-08-27 01:00",
                            "tmp": "21",
                            "wind_deg": "185",
                            "wind_dir": "南风",
                            "wind_sc": "1-2",
                            "wind_spd": "10"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "19",
                            "hum": "96",
                            "pop": "20",
                            "pres": "960",
                            "time": "2019-08-27 02:00",
                            "tmp": "21",
                            "wind_deg": "327",
                            "wind_dir": "西北风",
                            "wind_sc": "1-2",
                            "wind_spd": "7"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "19",
                            "hum": "96",
                            "pop": "20",
                            "pres": "959",
                            "time": "2019-08-27 03:00",
                            "tmp": "21",
                            "wind_deg": "181",
                            "wind_dir": "南风",
                            "wind_sc": "1-2",
                            "wind_spd": "1"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "19",
                            "hum": "95",
                            "pop": "20",
                            "pres": "959",
                            "time": "2019-08-27 04:00",
                            "tmp": "21",
                            "wind_deg": "177",
                            "wind_dir": "南风",
                            "wind_sc": "1-2",
                            "wind_spd": "8"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "19",
                            "hum": "95",
                            "pop": "20",
                            "pres": "959",
                            "time": "2019-08-27 05:00",
                            "tmp": "21",
                            "wind_deg": "336",
                            "wind_dir": "西北风",
                            "wind_sc": "1-2",
                            "wind_spd": "4"
                        },
                        {
                            "cloud": "100",
                            "cond_code": "305",
                            "cond_txt": "小雨",
                            "dew": "19",
                            "hum": "94",
                            "pop": "25",
                            "pres": "959",
                            "time": "2019-08-27 06:00",
                            "tmp": "21",
                            "wind_deg": "336",
                            "wind_dir": "西北风",
                            "wind_sc": "1-2",
                            "wind_spd": "4"
                        }
                    ]
                }
            ]
        },
        "airDto": {
            "HeWeather6": [
                {
                    "basic": {
                        "cid": "CN101110101",
                        "location": "西安",
                        "parent_city": "西安",
                        "admin_area": "陕西",
                        "cnty": "中国",
                        "lat": "34.26316071",
                        "lon": "108.94802094",
                        "tz": "+8.00"
                    },
                    "update": {
                        "loc": "2019-08-26 06:44",
                        "utc": "2019-08-25 22:44"
                    },
                    "status": "ok",
                    "air_now_city": {
                        "aqi": "88",
                        "qlty": "良",
                        "main": "PM2.5",
                        "pm25": "65",
                        "pm10": "107",
                        "no2": "22",
                        "so2": "9",
                        "co": "1.7",
                        "o3": "57",
                        "pub_time": "2019-08-26 06:00"
                    },
                    "air_forecast": [
                        {
                            "aqi": "111",
                            "date": "2019-08-25",
                            "main": "-",
                            "qlty": "轻度污染"
                        },
                        {
                            "aqi": "163",
                            "date": "2019-08-26",
                            "main": "-",
                            "qlty": "中度污染"
                        },
                        {
                            "aqi": "104",
                            "date": "2019-08-27",
                            "main": "-",
                            "qlty": "轻度污染"
                        },
                        {
                            "aqi": "39",
                            "date": "2019-08-28",
                            "main": "-",
                            "qlty": "优"
                        },
                        {
                            "aqi": "29",
                            "date": "2019-08-29",
                            "main": "-",
                            "qlty": "优"
                        },
                        {
                            "aqi": "23",
                            "date": "2019-08-30",
                            "main": "-",
                            "qlty": "优"
                        },
                        {
                            "aqi": "104",
                            "date": "2019-08-31",
                            "main": "-",
                            "qlty": "轻度污染"
                        }
                    ],
                    "air_now_station": [
                        {
                            "air_sta": "高压开关厂",
                            "asid": "CNA1462",
                            "lat": "34.2749",
                            "lon": "108.882",
                            "aqi": "89",
                            "qlty": "良",
                            "main": "PM2.5",
                            "pm25": "66",
                            "pm10": "91",
                            "no2": "22",
                            "so2": "10",
                            "co": "1.6",
                            "o3": "71",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "兴庆小区",
                            "asid": "CNA1463",
                            "lat": "34.2629",
                            "lon": "108.993",
                            "aqi": "77",
                            "qlty": "良",
                            "main": "PM10",
                            "pm25": "55",
                            "pm10": "104",
                            "no2": "26",
                            "so2": "5",
                            "co": "1.9",
                            "o3": "54",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "纺织城",
                            "asid": "CNA1464",
                            "lat": "34.2572",
                            "lon": "109.06",
                            "aqi": "87",
                            "qlty": "良",
                            "main": "PM2.5",
                            "pm25": "64",
                            "pm10": "115",
                            "no2": "31",
                            "so2": "5",
                            "co": "1.8",
                            "o3": "44",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "小寨",
                            "asid": "CNA1465",
                            "lat": "34.2324",
                            "lon": "108.94",
                            "aqi": "88",
                            "qlty": "良",
                            "main": "PM2.5",
                            "pm25": "65",
                            "pm10": "95",
                            "no2": "18",
                            "so2": "4",
                            "co": "1.6",
                            "o3": "52",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "市人民体育场",
                            "asid": "CNA1466",
                            "lat": "34.2713",
                            "lon": "108.954",
                            "aqi": "94",
                            "qlty": "良",
                            "main": "PM10",
                            "pm25": "65",
                            "pm10": "138",
                            "no2": "26",
                            "so2": "8",
                            "co": "1.6",
                            "o3": "58",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "高新西区",
                            "asid": "CNA1467",
                            "lat": "34.2303",
                            "lon": "108.883",
                            "aqi": "88",
                            "qlty": "良",
                            "main": "PM2.5",
                            "pm25": "65",
                            "pm10": "81",
                            "no2": "12",
                            "so2": "8",
                            "co": "1.6",
                            "o3": "65",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "经开区",
                            "asid": "CNA1468",
                            "lat": "34.3474",
                            "lon": "108.935",
                            "aqi": "102",
                            "qlty": "轻度污染",
                            "main": "PM2.5",
                            "pm25": "76",
                            "pm10": "87",
                            "no2": "18",
                            "so2": "10",
                            "co": "1.8",
                            "o3": "67",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "长安区",
                            "asid": "CNA1469",
                            "lat": "34.1546",
                            "lon": "108.906",
                            "aqi": "90",
                            "qlty": "良",
                            "main": "PM2.5",
                            "pm25": "67",
                            "pm10": "85",
                            "no2": "25",
                            "so2": "4",
                            "co": "1.6",
                            "o3": "53",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "阎良区",
                            "asid": "CNA1470",
                            "lat": "34.6575",
                            "lon": "109.2",
                            "aqi": "102",
                            "qlty": "轻度污染",
                            "main": "PM2.5",
                            "pm25": "76",
                            "pm10": "126",
                            "no2": "22",
                            "so2": "16",
                            "co": "1.8",
                            "o3": "65",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "临潼区",
                            "asid": "CNA1471",
                            "lat": "34.3731",
                            "lon": "109.2186",
                            "aqi": "90",
                            "qlty": "良",
                            "main": "PM10",
                            "pm25": "58",
                            "pm10": "129",
                            "no2": "17",
                            "so2": "10",
                            "co": "1.4",
                            "o3": "66",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "草滩",
                            "asid": "CNA1472",
                            "lat": "34.378",
                            "lon": "108.869",
                            "aqi": "85",
                            "qlty": "良",
                            "main": "PM10",
                            "pm25": "57",
                            "pm10": "120",
                            "no2": "12",
                            "so2": "14",
                            "co": "1.9",
                            "o3": "56",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "曲江文化产业集团",
                            "asid": "CNA1473",
                            "lat": "34.1978",
                            "lon": "108.985",
                            "aqi": "82",
                            "qlty": "良",
                            "main": "PM2.5",
                            "pm25": "60",
                            "pm10": "108",
                            "no2": "28",
                            "so2": "5",
                            "co": "1.6",
                            "o3": "39",
                            "pub_time": "2019-08-26 06:00"
                        },
                        {
                            "air_sta": "广运潭",
                            "asid": "CNA1474",
                            "lat": "34.3274",
                            "lon": "109.043",
                            "aqi": "80",
                            "qlty": "良",
                            "main": "PM2.5",
                            "pm25": "59",
                            "pm10": "102",
                            "no2": "28",
                            "so2": "9",
                            "co": "1.9",
                            "o3": "47",
                            "pub_time": "2019-08-26 06:00"
                        }
                    ]
                }
            ]
        }
    }
};